# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="blinks"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git gem rails rails3 ruby svn zsh-syntax-highlighting zsh-title)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

export PATH=$HOME/bin:$PATH

case $OSTYPE in 
darwin*)
    #PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    #MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    ;;
linux*)
    ;;
esac

alias vi="vim"
export EDITOR="vim"
export VISUAL="vim"

# for tmux: export screen-256color
[ -n "$TMUX" ] && export TERM="screen-256color" || export TERM="xterm-256color"

eval `dircolors ~/.dir_colors`

alias ls='ls --color=auto -h --group-directories-first'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias nomcopter='ssh -p 484 nomcopter@nomcopter.com'

# Source user-specific customizations.
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
